# Generated by Django 5.1.4 on 2024-12-20 02:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
