# Generated by Django 5.1.4 on 2024-12-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_institution_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='map',
            field=models.TextField(blank=True, help_text='Embed map URL.', null=True),
        ),
    ]
