# Generated by Django 5.1.4 on 2024-12-21 10:43

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_institution_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='foreign_university_name',
            new_name='Foreign_University_Name',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='principal_message',
            new_name='Principal_Message',
        ),
        migrations.AlterField(
            model_name='institution',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.logo_upload_to),
        ),
        migrations.AlterField(
            model_name='institution',
            name='map',
            field=models.TextField(blank=True, help_text='Embed map URL with width value 950 and height value 500.', null=True),
        ),
        migrations.CreateModel(
            name='InstitutionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=app.models.gallery_upload_to)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.institution')),
            ],
        ),
    ]
