# Generated by Django 5.1.4 on 2024-12-23 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_foreign_university_name_institution_foreign_university_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='institutionimage',
            table='Institution Images',
        ),
    ]
