# Generated by Django 5.1.4 on 2024-12-23 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_institutionimage_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstitutionImage',
            new_name='Institution_Image',
        ),
        migrations.AlterModelTable(
            name='institution_image',
            table=None,
        ),
    ]
