# Generated by Django 5.1.4 on 2024-12-23 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_institutionimage_institution_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Institution_Image',
            new_name='InstitutionImage',
        ),
    ]
