# Generated by Django 5.1.4 on 2024-12-28 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_institution_image_institutionimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
