# Generated by Django 5.1.4 on 2024-12-29 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_superadmin'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='institutionimage',
            table='Institution Images',
        ),
        migrations.AlterModelTable(
            name='superadmin',
            table='Super Admins',
        ),
    ]
