# Generated by Django 5.1.4 on 2024-12-29 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_institutionimage_table_alter_superadmin_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='institutionimage',
            table=None,
        ),
        migrations.AlterModelTable(
            name='superadmin',
            table=None,
        ),
    ]
