# Generated by Django 5.1.4 on 2024-12-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_institutionimage_table_alter_superadmin_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('show', 'Show'), ('hide', 'Hide')], default='hide', max_length=10),
        ),
    ]
