# Generated by Django 5.1.4 on 2024-12-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_feedback_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
