# Generated by Django 5.1.4 on 2024-12-30 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_feedback_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='Principal_Message',
            new_name='message',
        ),
    ]
