# Generated by Django 5.1.4 on 2024-12-30 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_institutionadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionadmin',
            name='phone',
        ),
    ]
