# Generated by Django 5.1.4 on 2024-12-31 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_institutionadmin_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='admin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_institution', to='app.institutionadmin'),
        ),
    ]
