# Generated by Django 5.1.4 on 2025-01-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_institution_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('abbreviation', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('field', models.CharField(choices=[('engineering', 'Engineering'), ('cit', 'Computer and Information Technology'), ('management', 'Management'), ('st', 'Science and Technology'), ('medicine', 'Medicine'), ('law', 'Law')], max_length=255)),
                ('affiliation', models.CharField(choices=[('tribhuvan', 'Tribhuvan University'), ('pokhara', 'Pokhara University'), ('kathmandu', 'Kathmandu University'), ('gandaki', 'Gandaki University'), ('purbanchal', 'Purbanchal University'), ('foreign', 'Foreign University')], max_length=50)),
                ('Foreign_University_Name', models.CharField(blank=True, help_text='If the affiliation is Foreign University, specify the university name here.', max_length=255, null=True)),
                ('about', models.TextField()),
                ('eligibility', models.TextField()),
                ('Admission_Criteria', models.TextField(blank=True, null=True)),
                ('Job_Prospect', models.TextField(blank=True, null=True)),
                ('Prospect_Career', models.TextField(blank=True, null=True)),
                ('Offered_by', models.ManyToManyField(blank=True, null=True, related_name='courses_offered', to='app.institution')),
            ],
        ),
    ]
