# Generated by Django 5.1.4 on 2025-01-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Offered_by',
            field=models.ManyToManyField(blank=True, related_name='courses_offered', to='app.institution'),
        ),
    ]
