# Generated by Django 5.1.4 on 2025-01-03 17:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_course_offered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master')], default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
