# Generated by Django 5.1.4 on 2025-01-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_course_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='eligibility',
            field=models.TextField(blank=True, null=True),
        ),
    ]
