# Generated by Django 5.1.4 on 2025-01-07 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_course_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Offered_by',
        ),
        migrations.CreateModel(
            name='InstitutionCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, help_text='Details specific to this course offered by the institution.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_courses', to='app.course')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_courses', to='app.institution')),
            ],
            options={
                'unique_together': {('institution', 'course')},
            },
        ),
    ]
