# Generated by Django 5.1.4 on 2025-01-08 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_visitorlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitorLog',
        ),
    ]
