# Generated by Django 5.1.4 on 2025-01-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_delete_visitorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff')], default='staff', max_length=10),
        ),
    ]
