# Generated by Django 5.1.4 on 2025-01-12 13:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_superadmin_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superadmin',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
