# Generated by Django 5.1.4 on 2025-01-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='admission',
            field=models.BooleanField(default=False, help_text='Toggle to enable or disable the admission period.'),
        ),
    ]
