# Generated by Django 5.1.4 on 2025-01-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_institution_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='current_admissions',
            field=models.IntegerField(default=0, help_text='Current admissions count.'),
        ),
        migrations.AddField(
            model_name='institution',
            name='last_admissions',
            field=models.IntegerField(default=0, help_text='Admissions count from the last admission period.'),
        ),
    ]
