# Generated by Django 5.1.4 on 2025-01-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_institution_current_admissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.CharField(blank=True, choices=[('province_1', 'Province No. 1'), ('province_2', 'Province No. 2'), ('bagmati', 'Bagmati Province'), ('gandaki', 'Gandaki Province'), ('lumbini', 'Lumbini Province'), ('karnali', 'Karnali Province'), ('sudurpashchim', 'Sudurpashchim Province')], max_length=100, null=True),
        ),
    ]
