# Generated by Django 5.1.4 on 2025-02-24 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_institution_average_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.institution'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
