# Generated by Django 5.1.4 on 2025-02-26 15:39

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_rating_institution_institutionview'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='Cover_Photo',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.cover_upload_to),
        ),
    ]
